### ISSUE TITLE
HGraphStorage-0.0.1 doesn't compile with GHC 7.8.x

### ISSUE THREAD

**Issue by peti** [JPMoresmau/HGraphStorage#1]
See http://hydra.cryp.to/build/526780/log/raw for a build log that shows the error messages.

**Comment by JPMoresmau** [comment]
Weird, since I have GHC 7.8.3 as well, and of course it builds fine... but Hackage agrees with you as well...

**Comment by peti** [comment]
Maybe ghc 7.8.4 is different in that regard?

**Comment by JPMoresmau** [comment]
Hackage is 7.8.3 as far as I can tell, which is my exact version...

**Comment by JPMoresmau** [comment]
It's monad-control, 1.0 broke the api. Constraint it to <1.0, I'm working on a patch

**Comment by JPMoresmau** [comment]
Released as 0.0.2
