### ISSUE TITLE
Compatibility with Neo4j

### ISSUE THREAD

**Issue by tkvogt** [JPMoresmau/HGraphStorage#3]
In the README you say: "inspired by the Neo4J format"
How much is it comptible with Neo4j?
Can I copy some files over to the graph.db folder in Neo4j and it is accepted?

**Comment by JPMoresmau** [comment]
No, it is not made to be compatible by the Neo4J format, I've just reused the ideas outlined in the book Graph Databases and in some technical documentation on Neo4J.
